export const NEWS_FETCH_DATA = "NEWS_FETCH_DATA";
export const NEWS_FETCH_SUCCESS = "NEWS_FETCH_SUCCESS";
export const NEWS_FETCH_ERR = "NEWS_FETCH_ERR";
export const NEWS_FETCH_END = "NEWS_FETCH_END";
